Bug5346 Listings not being created when listings/$HOST is a bad link.
Bug6142 did indeed catch the error, but did not cause an abort.

Added exit 1 if mkdir's exit status is an error.  This causes the
node to abort.

diff --git a/bin/nodetracer b/bin/nodetracer
--- a/bin/nodetracer
+++ b/bin/nodetracer
@@ -121,7 +121,8 @@ time_dest=${dest}.${datestamp}.`date +%T`
 rm -f $time_dest
 mkdir -p $dest_dir
 if [[ $? != 0 ]]; then
-    nodelogger -n $n $loopargs -s info -m "nodetracer error: cannot create directory $dest_dir"
+    nodelogger -n $n $loopargs -s abort -m "nodetracer error: cannot create directory $dest_dir"
+    exit 1
 fi
 
 #compress listing? 
