merge nodelister with datestamp

diff --git a/bin/nodelister b/bin/nodelister
--- a/bin/nodelister
+++ b/bin/nodelister
@@ -8,35 +8,54 @@
 #
 # description: shows the latest listing of the node 
 #
-# usage: nodelister -n node [-l loopargs] -type [success,abort] -d datestamp -list        - shows all the possible listings (successful, aborted)
+# usage: nodelister -n node [-l loopargs] -type [success,abort] -list  - shows all the possible listings (successful, aborted)
 #        nodelister -h                                         - shows help
-#        nodelister -n node -type [success,abort]              - shows the latest available listing (successful, aborted)
-#        nodelister -n node -type [success,abort] -o outfile   - outputs the latest available listing (successful, aborted) to file outfile
+#        nodelister -n node -type [success,abort] -d datestamp - shows the latest available listing (successful, aborted)
+#        nodelister -n node -type [success,abort] -d datestamp -o outfile   - outputs the latest available listing (successful, aborted) to file outfile
+#        nodelister -n node [-l loopargs] -type [success,abort] -d datestamp -list - shows all the possible listings (successful, aborted) for the specified datestamp
+#        nodelister -n node [-l loopargs] -type [success,abort] -d datestamp - shows one specific listing file
+
+function viewfile
+{
+   source_file=$1
+   dest_file=$2
+   if [[ -e ${source_file} ]]; then
+      if [[ ${dest_file} == "" ]]; then
+         gunzip -c ${source_file}
+      else
+         gunzip -c ${source_file} > ${dest_file}
+      fi
+   fi
+}
 
 Usage="
 Nodelister  \n 
 \n
 \t     Shows the latest listing of the node \n
 \n
-\t     Usage: nodelister -n node [-l loopargs] [-type [success,abort]] [-list -o outfile]\n 
+\t     Usage: nodelister -n node [-l loopargs] [-type [success,abort]] -d datestamp [-list -o outfile] [-f listfile] \n
 \n
 \t\t        Where: \n
 \t\t\t          node is the full node name. ex: /regional/assimilation/00/gen_cutoff \n
 \t\t\t          loopargs is the comma-separated list of loop arguments. ex. outer_loop=1,inner_loop=2\n
 \t\t\t          type defines whether to get the latest succesfull or aborted listing. Default is success.\n
+\t\t\t          datestamp is the experiment datestamp (YYYYMMDDhhmmss)\n
 \t\t\t          list shows all possible listings of the node.\n
 \t\t\t          outfile is the output file where the output can be redirected.\n
+\t\t\t\t        listfile is used for viewing specific listing instead of latest (requires full path to listing file)
+\t\t\t          node and listfile arguments are mutually exclusive but at least one must be provided
 \n
 \t     Ex: \n
 \t\t       nodelister -n node [-l loopargs] -type [success,abort] -d datestamp -list        - shows all the possible listings (successful, aborted)\n
 \t\t       nodelister -h                                                       - shows help\n
 \t\t       nodelister -n node -type [success,abort]                            - shows the latest available listing (successful, aborted)\n
 \t\t       nodelister -n node -type [success,abort] -o outfile                 - outputs the latest available listing (successful, aborted) to file outfile\n
+\t\t       nodelister -f listfile -o outfile                                   - outputs the specified listing file to file outfile\n
 \n
 \t     SEQ_EXP_HOME=$SEQ_EXP_HOME\n"
 
 arguments=$*
-eval `cclargs_lite $0 \
+eval `cclargs_lite -D "" $0 \
   -h        ""                    "1"                          "[Display help       ]" \
   -n        ""                    ""                           "[Node         ]" \
   -list     "0"                   "1"                          "[Show available listings            ]" \
@@ -44,7 +63,8 @@ eval `cclargs_lite $0 \
   -l        ""                    ""                           "[Loop argument list ]" \
   -o        ""                    "/tmp/nodelister_$$"         "[Output listing to file    ]" \
   -d        ""                    ""                           "[datestamp value]" \
-  ++ $arguments`
+  -f        ""                    ""                           "[Listing file full path]" \
+  ++ $arguments 2>/dev/null`
 
 if [ ! -d "${SEQ_EXP_HOME}" ]; then
    echo "nodelister error: Invalid path SEQ_EXP_HOME=$SEQ_EXP_HOME"
@@ -56,16 +76,33 @@ else
    nodeinfo=$(which nodeinfo)
 fi
 
-if [[ $n == "" ]]; then
-    echo "Node must be defined \n"
+if [[ $n == "" && $f == "" ]]; then
+    echo "Node or listing file must be defined \n"
     echo $Usage
     exit 1
 fi
 
-if [[ $d == "" && ${list} == "0" ]]; then
+if [[ $n != "" && $f != "" ]]; then
+    echo "Node or listing file are mutually exclusive\n"
+    echo $Usage
+    exit 1
+fi
+
+if [[ $f != "" ]]; then
+   if [[ -e $f ]]; then
+      viewfile $f $o
+   else
+      printf "File Not Found: $f\n"
+   fi
+   exit 0
+fi
+
+if [[ $n != "" ]]; then
+   if [[ $d == "" && ${list} == "0" ]]; then
     echo "Datestamp must be defined \n"
     echo $Usage
     exit 1
+   fi
 fi
 datestamp=$d
 
@@ -83,7 +120,6 @@ if [[ $l != "" ]]; then
 else
    fullnode=$n
 fi
-
 latest_dir=${SEQ_EXP_HOME}/listings/latest/
 
 if [ "$type" != "abort" -a "$type" != "success" ]; then
@@ -95,7 +131,7 @@ if [[ $list -eq 1 ]]; then
    hostlist=$(ls -L ${SEQ_EXP_HOME}/listings | grep -wv latest | sed "s/\//\ /")
    for host in $hostlist ; do
       echo On $host
-      ssh $host ls -alrt ${SEQ_EXP_HOME}/listings/$host/$fullnode.$type.gz.${datestamp}* 2>/dev/null 
+      ssh $host ls -alrt ${SEQ_EXP_HOME}/listings/$host/${fullnode}*.${type}.gz.${datestamp}* 2>/dev/null 
    done
 else 
        latestlink=$(ls -rt1 $latest_dir/$fullnode.${datestamp}.$type@* 2> /dev/null | tail -1)
@@ -116,3 +152,4 @@ else
        fi
        test $found == 0 && echo $fullnode $type 'listing not available'
 fi
+
